name: deploy type-room-web

on:
  push:
    branches:
      - "main" # 针对 main 分支
    paths:
      - ".github/workflows/*"
      - "src/**"
      - "public/*"
      - "package.json"
      - "vite.config.ts"
      - "index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v3

      - name: 设置 node 环境
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: 安装依赖
        run: yarn

      - name: 编译打包
        run: yarn build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.VORTESNAIL_ID_RSA }}
            ARGS: '-rltgoDzvO --delete'
            SOURCE: dist # 这是要复制到阿里云静态服务器的文件夹名称
            REMOTE_HOST: ${{secrets.REMOTE_WEB_DIR}} # 你的阿里云公网地址
            REMOTE_USER: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
            TARGET: ${{secrets.REMOTE_WEB_DIR}} # 打包后的 dist 文件夹将放在 /root/node-server

